apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-gitops-operator-controller-manager
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
- name: open-cluster-management-image-pull-credentials
