apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-gitops-operator-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: openshift-gitops-operator-controller-manager
  namespace: {{ .Release.Namespace }}
