apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: gitops-addon-config
  namespace: open-cluster-management
spec:
  customizedVariables:
  - name: GITOPS_OPERATOR_IMAGE
    value: registry.redhat.io/openshift-gitops-1/gitops-rhel8-operator@sha256:2a932c0397dcd29a75216a7d0467a640decf8651d41afe74379860035a93a6bd
  - name: GITOPS_OPERATOR_NAMESPACE
    value: openshift-gitops-operator
  - name: GITOPS_IMAGE
    value: registry.redhat.io/openshift-gitops-1/argocd-rhel8@sha256:94e19aca2c330ec15a7de3c2d9309bb2e956320ef29dae2df3dfe6b9cad4ed39
  - name: GITOPS_NAMESPACE
    value: openshift-gitops
  - name: REDIS_IMAGE
    value: registry.redhat.io/rhel9/redis-7@sha256:848f4298a9465dafb7ce9790e991bd8a11de2558e3a6685e1d7c4a6e0fc5f371
  - name: RECONCILE_SCOPE
    value: Single-Namespace
  - name: ARGOCD_AGENT_ENABLED
    value: "false"
  - name: ARGOCD_AGENT_IMAGE
    # Default value - can be overridden via GitOpsCluster.spec.gitOpsAddon.argoCDAgent.image
    value: registry.redhat.io/openshift-gitops-1/argocd-agent-rhel8@sha256:d17069d475959a5fca31dc4cd2c2dce4f3d895f2c2b97906261791674a889079
  - name: ARGOCD_AGENT_SERVER_ADDRESS
    value: ""
  - name: ARGOCD_AGENT_SERVER_PORT
    value: ""
  - name: ARGOCD_AGENT_MODE
    value: "managed"
