org: open-cluster-management

nameOverride: openshift-gitops-operator
fullnameOverride: openshift-gitops-operator

global: 
  openshift_gitops_operator:
    image: ""
    tag: ""
  gitops_service:
    image: ""
    tag: ""
  gitops_console_plugin:
    image: ""
    tag: ""
  proxyConfig:
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
    NO_PROXY: ""
